### ISSUE TITLE
Dismiss action

### ISSUE THREAD

**Issue by justintadlock** [WPTRT/admin-notices#1]
Anyone with an vanilla JS or code in general to point to for handling the dismiss action for an admin notice would be much appreciated.

**Comment by pattonwebz** [comment]
I have seen mostly storage of the dismiss handled in `user_meta`. If we go down the route of user meta would an ajax endpoint be suitable? It seems like somewhat of an overkill solution but I can't immediately think of anything better.

**Comment by DannyCooper** [comment]
If you didn't want to go down the JS route, I believe it can be done like this:

```
/**
 * Display the admin notice.
 */
function scaffold_admin_notice() {
	global $current_user;
	$user_id = $current_user->ID;
	if ( ! get_user_meta( $user_id, 'scaffold_ignore_customizer_notice' ) ) {
		?>

		<div class="notice notice-info">
			<p>
				<strong>New!</strong> Easily customize your Scaffold theme design with our new settings - <a target="_blank" href="https://docs.olympusthemes.com/kb/scaffold-theme/customizer-settings-scaffold/?utm_source=notice">Learn More</a>
				<span style="float:right">
					<a href="?scaffold_ignore_customizer_notice=0"><?php esc_html_e( 'Hide Notice', 'scaffold' ); ?></a>
				</span>
			</p>
		</div>

		<?php
	}
}
add_action( 'admin_notices', 'scaffold_admin_notice' );
/**
 * Dismiss the admin notice.
 */
function scaffold_dismiss_admin_notice() {
	global $current_user;
	$user_id = $current_user->ID;
	/* If user clicks to ignore the notice, add that to their user meta */
	if ( isset( $_GET['scaffold_ignore_customizer_notice'] ) && '0' === $_GET['scaffold_ignore_customizer_notice'] ) {
		add_user_meta( $user_id, 'scaffold_ignore_customizer_notice', 'true', true );
	}
}
add_action( 'admin_init', 'scaffold_dismiss_admin_notice' );
```

**Comment by DannyCooper** [comment]
I found an existing library which might serve as inspiration for this project - https://github.com/alessandrotesoro/wp-notices

**Comment by ernilambar** [comment]
Helpful may be for inspiration - https://github.com/julien731/WP-Dismissible-Notices-Handler

**Comment by aristath** [comment]
I just pushed the initial commit for this package a few minutes ago.
Dismiss is handled using Vanilla JS and I added usage instructions in the readme file.

If anyone has any suggestions on how to improve this - or if you believe we should do something differently, please let me know. 👍 

@justintadlock I could not add the package on packagist, apparently I need to be added as a as a maintainer in that vendor namespace first (which is why I didn't write the "installation" section in the readme yet).

**Comment by aristath** [comment]
Right now it defaults to saving an `option`, so the scope of dismissing the notices is global. Do you think that the default should be saving as post-meta? It's easy to change, we just need to tweak the default for the `scope` argument from `global` to `user` here: https://github.com/WPTRT/admin-notices/blob/26b8acd8a434ae852ef4baf1ecec41459111f486/src/Notice.php#L58-L65

**Comment by justintadlock** [comment]
@aristath - You're a maintainer now: https://packagist.org/packages/wptrt/admin-notices

**Comment by aristath** [comment]
Closing this one.

Changed the implementation a bit based on code from #2 and posted a pre-release announcement on https://wordpress.slack.com/archives/C02RP4Y3K/p1567946320196600

I'll post again in the WPTRT channel on slack in a couple of days, see if anyone has any questions/remarks/suggestions that we want to implement. I'll wait a few days for feedback before tagging `v1.0`.
