### ISSUE TITLE
allow full HTML in notices

### ISSUE THREAD

**Issue by mnelson4** [WPTRT/admin-notices#12]
It's cumbersome and unnecessary to restrict what HTML can be used inside notices. For example, it's common to want to add a form, or embed a video, or a million other things than [what's allowed](https://github.com/WPTT/admin-notices/blob/master/src/Notice.php#L270). 
What's more, these notices are added by the *developer*, who has full access to the code and database. They have much more direct methods to hack a website than adding malicious JS.
I would suggest all that code relating to restricting what HTML tags can be used inside notices should be removed.

**Comment by aristath** [comment]
This package is a good way for theme-authors to implement notices the way they should be implemented. 
A notice should not contain forms, videos or a million other things. A notice's purpose is to notify users. It is not a place for developers to add all their promotional material. Sure, developers _can_ add whatever they want... but they should not. 
A notice can be used to say _"hey user, check out our admin page to register, see the form, videos, FAQs or whatever you want"_, but it should not be used to directly add these things to the dashboard. That's what admin-pages are for.
The allowed list is a good way to restrict things and promote good practices. Adding in the content of a notice things that should not be there could result in a theme failing the review process in the wordpress.org repository so I don't think it will be removed...

**Comment by mnelson4** [comment]
Thanks for the explanation of the rationale behind the restriction (I incorrectly thought it’s purpose was security, not encouraging best practices.)
And ya I think that definition of what *should* go into notices sounds good, but I think lots of developers have noticed that extra clicks means less engagement (eg if folks need to click a link to then signup for something, rather than signup for something right away, you’ll lose about half the signups.) I’m kinda under the impression that lots of big plugins and themes routinely put a lot more in notices. But I don’t have any concrete examples at hand, and I admit whether they do and whether they should are different questions.
So maybe consider this a vote to encourage allowing other HTML in notices.
But your explanation of the rationale is satisfactory, thank you.
