### ISSUE TITLE
Class / Style attributes stripped from allowed tags

### ISSUE THREAD

**Issue by woodwardmatt** [WPTRT/admin-notices#13]
Hi All, 

Was trying out your package recently and noted that it stripped the class / style attributes from the em tag I was trying to use in the admin notice content. In my case this was to add some (font awesome) icons to the notice. 

Is there any appetite to allow the class / style attributes on the allowed tags for this use case?

**Comment by aristath** [comment]
Not by default. You can tweak the script to your liking when including it in your theme, but the "default" is to strip these things and keep notices as simple as possible, following the theme-review guidelines. :+1:
