### ISSUE TITLE
Original Project Code

### ISSUE THREAD

**Issue by justintadlock** [WPTRT/admin-notices#2]
I meant to push this live ages ago but forgot.  I'm just opening this ticket to share the original code that I threw together.  Feel free to use any bits and pieces or discard it altogether.  There might be an idea or two worth looking at in there.

[admin-notices.zip](https://github.com/WPTRT/admin-notices/files/3586955/admin-notices.zip)

**Comment by justintadlock** [comment]
And, code example to test the above: 

```php
use WPTRT\AdminNotices\Notices;

add_action( 'admin_notices', function() {

	$notices = new Notices();

	$notices->add( 'a', 'Info with normal style.', [ 'type' => 'info' ] );
	$notices->add( 'b', 'Info with alt style.', [ 'type' => 'info', 'alt_style' => true ] );

	$notices->add( 'c', 'Success with normal style.', [ 'type' => 'success' ] );
	$notices->add( 'd', 'Success with alt style.', [ 'type' => 'success', 'alt_style' => true ] );

	$notices->add( 'e', 'Warning with normal style.', [ 'type' => 'warning' ] );
	$notices->add( 'f', 'Warning with alt style.', [ 'type' => 'warning', 'alt_style' => true ] );

	$notices->add( 'g', 'Error with normal style.', [ 'type' => 'error' ] );
	$notices->add( 'h', 'Error with alt style.', [ 'type' => 'error', 'alt_style' => true ] );

	// Display notices.
	$notices->display();

	// @todo enqueue JS.

} );
```

**Comment by aristath** [comment]
Thanks @justintadlock!

I took a lot of that code and refactored the package.
It is now a mix of the two implementations, details are in the [readme](https://github.com/WPTRT/admin-notices/blob/master/readme.md) file.
